In [1]:
# import the Libraries
import numpy as np                # used for vMulti dimensional array
import pandas as pd               # used for import the dataset
import matplotlib.pyplot as plt   # used for ploting the Graph
from sklearn import metrics

In [2]:
dataset=pd.read_csv('second_hand_Car_price.csv')


In [3]:
dataset.head()

v.id  on road old  on road now  years      km  rating  condition  economy  \
0     1       535651       798186      3   78945       1          2       14   
1     2       591911       861056      6  117220       5          9        9   
2     3       686990       770762      2  132538       2          8       15   
3     4       573999       722381      4  101065       4          3       11   
4     5       691388       811335      6   61559       3          9       12   

   top speed  hp  torque  current price  
0        177  73     123       351318.0  
1        148  74      95       285001.5  
2        181  53      97       215386.0  
3        197  54     116       244295.5  
4        160  53     105       531114.5

In [4]:
ds=dataset.drop(['v.id'],axis=1)

In [5]:
ds.head()

on road old  on road now  years      km  rating  condition  economy  \
0       535651       798186      3   78945       1          2       14   
1       591911       861056      6  117220       5          9        9   
2       686990       770762      2  132538       2          8       15   
3       573999       722381      4  101065       4          3       11   
4       691388       811335      6   61559       3          9       12   

   top speed  hp  torque  current price  
0        177  73     123       351318.0  
1        148  74      95       285001.5  
2        181  53      97       215386.0  
3        197  54     116       244295.5  
4        160  53     105       531114.5

In [6]:
x=ds.iloc[:,:-1].values   
y=ds.iloc[:,-1].values 

In [7]:
x

array([[535651, 798186,      3, ...,    177,     73,    123],
       [591911, 861056,      6, ...,    148,     74,     95],
       [686990, 770762,      2, ...,    181,     53,     97],
       ...,
       [646344, 842733,      7, ...,    196,    113,     89],
       [535559, 732439,      2, ...,    184,    112,    128],
       [590105, 779743,      5, ...,    199,     99,     96]], dtype=int64)

In [8]:
y

array([351318. , 285001.5, 215386. , 244295.5, 531114.5, 177933.5,
       410877. , 467471.5, 462397.5, 197266. , 292308.5, 264576.5,
       515454. , 373529. , 474281.5, 468666. , 210661.5, 274357.5,
       439639.5, 196816. , 112864.5, 427079. , 337327. , 140216.5,
       518845. , 381846.5, 337917. , 322684. , 173847. , 291031.5,
       347784.5, 459914.5, 177748.5, 166283. , 317119. , 195854. ,
       130233.5, 421781. , 316184. , 250955. , 397522. , 450198.5,
       315542.5, 435007.5, 140596. , 389925.5, 293875.5, 317681.5,
       413066. , 340760. , 230090.5, 108741. , 530759. , 151474. ,
       242173.5, 360008. , 382461.5, 444625. , 457581. , 381351.5,
       258300. , 116254.5, 171620. , 483708.5, 389512. , 203811.5,
       325176. , 300499.5, 309455. , 304216.5, 206335.5, 475273.5,
       468543. , 529318.5, 124847.5, 295002. , 153991. , 206591. ,
       298023. , 221412.5, 424781. , 413288. , 315403.5, 498148. ,
       336181.5, 350647.5, 160150.5, 353318. , 370175. , 42966

In [44]:
# spliting the dataset into test set and train set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=0)

In [45]:
x_train

array([[677780, 888243,      4, ...,    165,    119,    121],
       [620112, 850548,      5, ...,    171,     51,    120],
       [502794, 773887,      4, ...,    151,     50,    124],
       ...,
       [600974, 835783,      5, ...,    149,     70,    120],
       [560706, 847060,      7, ...,    163,     76,    128],
       [674576, 753775,      5, ...,    175,    104,    125]], dtype=int64)

In [46]:
y_train

array([510929. , 309455. , 146787. , 582347. , 471527.5, 140061.5,
       382241. , 153381.5, 227845.5, 322368. , 559074. , 461900.5,
       248119.5, 112864.5, 294378.5, 178180.5, 207480.5, 172758.5,
       475273.5, 340760. , 459833.5, 288556.5, 260231. , 457880.5,
       177509.5, 153991. , 413066. , 415103. , 122225.5, 128632.5,
       387089. , 198892. , 389512. , 108921.5, 530759. , 405505. ,
       342427. , 215633.5, 446487.5, 340777. , 469956. , 385248.5,
       269532.5, 515454. , 255901.5, 413424.5, 104215. , 293875.5,
       245796. , 126070.5, 414035. , 520084. , 326161.5, 202883.5,
       407127.5, 499121. ,  53040. , 218983.5, 150234.5, 335093.5,
       549406. , 274357.5, 398998. , 241487.5, 492951. , 157507. ,
       426760. , 238941. , 354409.5, 296565.5, 187305. , 558253. ,
       224533.5, 158511. , 425960. , 496671. , 183465.5, 254581. ,
       340112. , 298023. , 383570.5, 111175.5, 152879.5, 287093.5,
       273761. , 369149. , 153371.5, 275045.5, 427079. , 30242

In [47]:
x_test

array([[601042, 756860,      2, ...,    170,     99,     98],
       [589700, 754619,      2, ...,    143,     89,    110],
       [547887, 721567,      7, ...,    147,     97,    119],
       ...,
       [520389, 757603,      3, ...,    194,     73,    135],
       [679306, 783183,      5, ...,    161,    106,    100],
       [669458, 782853,      7, ...,    164,     87,    113]], dtype=int64)

In [48]:
y_test

array([307255. , 380928.5, 121022. , 174352.5, 190949. , 283248. ,
       322684. , 309449. , 182219.5, 352345. , 318858. , 102144.5,
       307770.5, 490000.5, 232718.5, 360008. , 265194. , 464634.5,
       474281.5, 206591. , 459914.5, 207552. , 392864. , 423507. ,
       239923. , 301042.5, 389925.5, 349762. , 156513. , 285001.5,
       208573.5, 232826.5, 239018. , 274172. , 328863. , 187050. ,
       233987. , 360737.5, 354722. , 404800.5, 420075.5, 419748. ,
       331263.5,  97526. , 208468. , 192576. , 424290. , 163225. ,
       187009. , 451140.5, 267953.5, 458463.5,  94467.5, 216327. ,
       274650. , 349780. , 458139. , 441865. , 311109. , 184092.5,
       376267.5, 165595. , 272437.5, 304923.5, 188131.5, 344820.5,
       492681.5, 328973.5, 286937.5, 371227. , 292520.5, 538075.5,
       146223. , 483663.5, 312469. , 126957.5, 153375.5, 316652. ,
       452931. , 469084.5, 348000. , 441863.5,  98489.5, 515722.5,
       467395. ,  65467.5, 296829. , 287675. , 240353.5, 21254

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
regressor=LinearRegression()
regressor

LinearRegression()

In [51]:
regressor.fit(x_train,y_train)

LinearRegression()

In [52]:
y_pred_test=regressor.predict(x_test)

In [53]:
y_pred_train=regressor.predict(x_train)

In [54]:
y_pred_train

array([500421.28397394, 304144.74591188, 153942.2262733 , 582578.7844688 ,
       472925.43513791, 122167.92426202, 392239.14738047, 152486.17102549,
       236395.92217732, 314842.84094986, 557404.96137085, 464706.06364262,
       228830.52173449, 120127.74815047, 304120.18409522, 188796.49148943,
       201505.75885506, 163622.18960674, 468377.18638539, 337615.8923658 ,
       440989.27854535, 286408.76654144, 268459.24464775, 457746.41904013,
       172757.45977527, 154566.25238604, 421107.49180453, 422147.08176662,
       127895.87971797, 136109.41325925, 395968.94668412, 189842.29574002,
       385282.63357272, 106453.0895936 , 520004.86818206, 402543.22123472,
       351060.96845038, 226755.31951261, 454397.61701923, 320435.51297431,
       475398.06983091, 390809.42728673, 272032.1072176 , 512314.35045916,
       264790.47150814, 421321.03132591, 113637.78190248, 288017.16510157,
       251382.89297086, 132103.79799345, 412804.26654755, 506927.02336678,
       323589.28292156, 2

In [55]:
y_train

array([510929. , 309455. , 146787. , 582347. , 471527.5, 140061.5,
       382241. , 153381.5, 227845.5, 322368. , 559074. , 461900.5,
       248119.5, 112864.5, 294378.5, 178180.5, 207480.5, 172758.5,
       475273.5, 340760. , 459833.5, 288556.5, 260231. , 457880.5,
       177509.5, 153991. , 413066. , 415103. , 122225.5, 128632.5,
       387089. , 198892. , 389512. , 108921.5, 530759. , 405505. ,
       342427. , 215633.5, 446487.5, 340777. , 469956. , 385248.5,
       269532.5, 515454. , 255901.5, 413424.5, 104215. , 293875.5,
       245796. , 126070.5, 414035. , 520084. , 326161.5, 202883.5,
       407127.5, 499121. ,  53040. , 218983.5, 150234.5, 335093.5,
       549406. , 274357.5, 398998. , 241487.5, 492951. , 157507. ,
       426760. , 238941. , 354409.5, 296565.5, 187305. , 558253. ,
       224533.5, 158511. , 425960. , 496671. , 183465.5, 254581. ,
       340112. , 298023. , 383570.5, 111175.5, 152879.5, 287093.5,
       273761. , 369149. , 153371.5, 275045.5, 427079. , 30242

In [64]:
y_train

array([510929. , 309455. , 146787. , 582347. , 471527.5, 140061.5,
       382241. , 153381.5, 227845.5, 322368. , 559074. , 461900.5,
       248119.5, 112864.5, 294378.5, 178180.5, 207480.5, 172758.5,
       475273.5, 340760. , 459833.5, 288556.5, 260231. , 457880.5,
       177509.5, 153991. , 413066. , 415103. , 122225.5, 128632.5,
       387089. , 198892. , 389512. , 108921.5, 530759. , 405505. ,
       342427. , 215633.5, 446487.5, 340777. , 469956. , 385248.5,
       269532.5, 515454. , 255901.5, 413424.5, 104215. , 293875.5,
       245796. , 126070.5, 414035. , 520084. , 326161.5, 202883.5,
       407127.5, 499121. ,  53040. , 218983.5, 150234.5, 335093.5,
       549406. , 274357.5, 398998. , 241487.5, 492951. , 157507. ,
       426760. , 238941. , 354409.5, 296565.5, 187305. , 558253. ,
       224533.5, 158511. , 425960. , 496671. , 183465.5, 254581. ,
       340112. , 298023. , 383570.5, 111175.5, 152879.5, 287093.5,
       273761. , 369149. , 153371.5, 275045.5, 427079. , 30242

In [63]:
y_pred_train

array([500421.28397394, 304144.74591188, 153942.2262733 , 582578.7844688 ,
       472925.43513791, 122167.92426202, 392239.14738047, 152486.17102549,
       236395.92217732, 314842.84094986, 557404.96137085, 464706.06364262,
       228830.52173449, 120127.74815047, 304120.18409522, 188796.49148943,
       201505.75885506, 163622.18960674, 468377.18638539, 337615.8923658 ,
       440989.27854535, 286408.76654144, 268459.24464775, 457746.41904013,
       172757.45977527, 154566.25238604, 421107.49180453, 422147.08176662,
       127895.87971797, 136109.41325925, 395968.94668412, 189842.29574002,
       385282.63357272, 106453.0895936 , 520004.86818206, 402543.22123472,
       351060.96845038, 226755.31951261, 454397.61701923, 320435.51297431,
       475398.06983091, 390809.42728673, 272032.1072176 , 512314.35045916,
       264790.47150814, 421321.03132591, 113637.78190248, 288017.16510157,
       251382.89297086, 132103.79799345, 412804.26654755, 506927.02336678,
       323589.28292156, 2

In [66]:
print('Mean Absolute Error:',metrics.mean_absolute_error(y_train,y_pred_train))

Mean Absolute Error: 7406.815850886314


In [59]:
print('Mean Squared Error:',metrics.mean_squared_error(y_test,y_pred_test))
print('Root Mean Squared Error:',np.sqrt(metrics.mean_squared_error(y_test,y_pred_test)))

Mean Squared Error: 69655807.30550712
Root Mean Squared Error: 8346.00547001421


In [71]:
#on road old	on road now	years	km	rating	condition	economy	top speed	hp	torque	current price
Xnew = [[535651,798186,3,78945,1,2,14,177,73,123]]

ynew = regressor.predict(Xnew)

print(ynew)

[345038.56127296]


In [73]:
from sklearn.metrics import accuracy_score

In [79]:
print("Accuracy : ", regressor.score(x_test, y_test))


Accuracy :  0.9950822625530568
